#!/bin/bash

# Installation script for minimal desktop environment.

# TODO: Check return values (https://google.github.io/styleguide/shellguide.html#s8.1-checking-return-values)!

if ! sudo true; then
  exit 1
fi

sudo dpkg-reconfigure tzdata

sudo apt-get update
sudo apt-get --yes upgrade

PACKAGES=(
  bc
  fbpanel
  feh
  file
  firefox-esr
  gawk
  git
  numix-gtk-theme
  numix-icon-theme
  onboard
  openbox
  rpd-wallpaper
  scrot
  vim
  xorg
  xterm
)
sudo apt-get --yes install "${PACKAGES[@]}"

sudo apt-get --yes autoremove
sudo apt-get --yes autoclean

sudo mkdir --parents "/usr/share/fonts/opentype/"
sudo git clone --branch release --depth 1 https://github.com/adobe-fonts/source-code-pro.git "/usr/share/fonts/opentype/source-code-pro"
sudo git clone --branch release --depth 1 https://github.com/adobe-fonts/source-sans.git "/usr/share/fonts/opentype/source-sans"
sudo git clone --branch release --depth 1 https://github.com/adobe-fonts/source-serif.git "/usr/share/fonts/opentype/source-serif"
sudo fc-cache -f -v "/usr/share/fonts/opentype/"

sudo tee /etc/vimrc <<- EOF
	runtime! archlinux.vim
	let skip_defaults_vim=1
	set expandtab
	set ignorecase
	set smartcase
	set shiftwidth=4
	set softtabstop=4
	set tabstop=4
	syntax on
EOF
sudo update-alternatives --set editor /usr/bin/vim.basic

sudo tee /etc/X11/xorg.conf.d/90-default.conf <<-EOF
	Section "ServerFlags"
	    Option "DontVTSwitch" "true"
	EndSection

	Section "ServerLayout"
	    Identifier "Display off"
	    Option "StandbyTime" "0"
	    Option "SuspendTime" "0"
	    Option "OffTime" "0"
	    Option "BlankTime" "0"
	EndSection
EOF

sudo mkdir --parents /etc/gtk-2.0/
sudo tee /etc/gtk-2.0/gtkrc <<-EOF
	gtk-theme-name = "Numix"
	gtk-icon-theme-name = "Numix"
	gtk-font-name = "Source Sans 3 12"
EOF
sudo mkdir --parents /etc/gtk-3.0/
sudo tee /etc/gtk-3.0/settings.ini <<-EOF
	[Settings]
	gtk-theme-name = Numix
	gtk-icon-theme-name = Numix
	gtk-font-name = Source Sans 3 12
EOF

mkdir --parents "${HOME}/.config/openbox/"
tee "${HOME}/.config/openbox/autostart" <<-EOF
	xrandr --auto
	feh --bg-scale /usr/share/rpd-wallpaper/sand.jpg
	fbpanel &
	onboard &
EOF
tee "${HOME}/.config/openbox/menu.xml" <<-EOF
	<?xml version="1.0" encoding="UTF-8"?>
	<openbox_menu>
	  <menu id="desktop" label="Auf zum Atem!">
	    <item label="Terminal">
	      <action name="Execute"><command>xterm</command></action>
	    </item>
	  </menu>
	</openbox_menu>
EOF
tee "${HOME}/.config/openbox/rc.xml" <<-EOF
	<?xml version="1.0" encoding="UTF-8"?>
	<openbox_config>
	  <theme>
	    <name>Numix</name>
	    <font place="ActiveWindow">
	      <name>Source Sans 3</name>
	      <size>14</size>
	      <weight>Bold</weight>
	    </font>
	    <font place="InactiveWindow">
	      <name>Source Sans 3</name>
	      <size>14</size>
	      <weight>Bold</weight>
	    </font>
	    <font place="MenuHeader">
	      <name>Source Sans 3</name>
	      <size>16</size>
	      <weight>Normal</weight>
	    </font>
	    <font place="MenuItem">
	      <name>Source Sans 3</name>
	      <size>16</size>
	      <weight>Normal</weight>
	    </font>
	    <titleLayout>LIMC</titleLayout>
	  </theme>
	  <desktops>
	    <number>1</number>
	    <firstdesk>1</firstdesk>
	    <names>
	      <name>Auf zum Atem!</name>
	    </names>
	  </desktops>
	  <keyboard>
	    <keybind key="W-Return">
	      <action name="Execute"><command>xterm</command></action>
	    </keybind>
	    <keybind key="W-Up">
	      <action name="Maximize"/>
	    </keybind>
	    <keybind key="W-Down">
	      <action name="Unmaximize"/>
	    </keybind>
	    <keybind key="W-Left">
	      <action name="Unmaximize"/>
	      <action name="MoveResizeTo">
	        <x>0</x>
	        <y>0</y>
	        <height>100%</height>
	        <width>50%</width>
	      </action>
	    </keybind>
	    <keybind key="W-Right">
	      <action name="Unmaximize"/>
	      <action name="MoveResizeTo">
	        <x>-0</x>
	        <y>0</y>
	        <height>100%</height>
	        <width>50%</width>
	      </action>
	    </keybind>
	    <keybind key="Print">
	      <action name="Execute"><command>scrot "%Y-%m-%d-%H-%M-%S.png"</command></action>
	    </keybind>
	  </keyboard>
	  <mouse>
	    <context name="Root">
	      <mousebind button="Right" action="Press">
	        <action name="ShowMenu">
	          <menu>desktop</menu>
	        </action>
	      </mousebind>
	    </context>
	    <context name="Titlebar">
	      <mousebind button="Left" action="Press">
	        <action name="Focus"/>
	        <action name="Raise"/>
	      </mousebind>
	      <mousebind button="Left" action="Drag">
	        <action name="Move"/>
	      </mousebind>
	      <mousebind button="Left" action="DoubleClick">
	        <action name="ToggleMaximize"/>
	      </mousebind>
	    </context>
	    <context name="Top">
	      <mousebind button="Left" action="Press">
	        <action name="Focus"/>
	        <action name="Raise"/>
	      </mousebind>
	      <mousebind button="Left" action="Drag">
	        <action name="Resize"><edge>top</edge></action>
	      </mousebind>
	    </context>
	    <context name="Left">
	      <mousebind button="Left" action="Press">
	        <action name="Focus"/>
	        <action name="Raise"/>
	      </mousebind>
	      <mousebind button="Left" action="Drag">
	        <action name="Resize"><edge>left</edge></action>
	      </mousebind>
	    </context>
	    <context name="Right">
	      <mousebind button="Left" action="Press">
	        <action name="Focus"/>
	        <action name="Raise"/>
	      </mousebind>
	      <mousebind button="Left" action="Drag">
	        <action name="Resize"><edge>right</edge></action>
	      </mousebind>
	    </context>
	    <context name="Bottom">
	      <mousebind button="Left" action="Press">
	        <action name="Focus"/>
	        <action name="Raise"/>
	      </mousebind>
	      <mousebind button="Left" action="Drag">
	        <action name="Resize"><edge>bottom</edge></action>
	      </mousebind>
	    </context>
	    <context name="TRCorner BRCorner TLCorner BLCorner">
	      <mousebind button="Left" action="Press">
	        <action name="Focus"/>
	        <action name="Raise"/>
	      </mousebind>
	      <mousebind button="Left" action="Drag">
	        <action name="Resize"/>
	      </mousebind>
	    </context>
	    <context name="Iconify">
	      <mousebind button="Left" action="Press">
	        <action name="Focus"/>
	        <action name="Raise"/>
	      </mousebind>
	      <mousebind button="Left" action="Click">
	        <action name="Iconify"/>
	      </mousebind>
	    </context>
	    <context name="Maximize">
	      <mousebind button="Left" action="Press">
	        <action name="Focus"/>
	        <action name="Raise"/>
	      </mousebind>
	      <mousebind button="Left" action="Click">
	        <action name="ToggleMaximize"/>
	      </mousebind>
	    </context>
	    <context name="Close">
	      <mousebind button="Left" action="Press">
	        <action name="Focus"/>
	        <action name="Raise"/>
	      </mousebind>
	      <mousebind button="Left" action="Click">
	        <action name="Close"/>
	      </mousebind>
	    </context>
	    <context name="Client">
	      <mousebind button="Left" action="Press">
	        <action name="Focus"/>
	        <action name="Raise"/>
	      </mousebind>
	      <mousebind button="Middle" action="Press">
	        <action name="Focus"/>
	        <action name="Raise"/>
	      </mousebind>
	      <mousebind button="Right" action="Press">
	        <action name="Focus"/>
	        <action name="Raise"/>
	      </mousebind>
	    </context>
	  </mouse>
	  <applications>
	    <application class="Firefox*">
	      <decor>no</decor>
	     </application>
	  </applications>
	</openbox_config>
EOF

mkdir --parents "${HOME}/.config/fbpanel/"
tee "${HOME}/.config/fbpanel/default" <<-EOF
	Global {
	    allign = center
	    autohide = false
	    edge = bottom
	    roundcorners = false
	    setdocktype = true
	    setpartialstrut = true
	    transparent = false
	}

	Plugin {
	    type = menu
	    config {
	        iconsize = 32
	        icon = open-menu-symbolic
	        item {
	            name = Firefox
	            icon = firefox-esr
	            action = firefox-esr
	        }
	        item {
	            name = Terminal
	            icon = terminal
	            action = xterm
	        }
	        separator {
	        }
	        item {
	            name = Reboot
	            icon = gnome-session-reboot
	            action = sudo reboot
	        }
	        item {
	            name = Shutdown
	            icon = gnome-session-halt
	            action = sudo shutdown -h now
	        }
	    }
	}

	Plugin {
	    type = taskbar
	    expand = true
	    config {
	        showmapped    = true
	        showalldesks  = true
	        tooltips = false
	        iconsonly = false
	        maxtaskwidth = 200
	    }
	}

	Plugin {
	    type = tclock
	    config {
	        ClockFmt = %R
	        ShowCalendar = false
	        ShowTooltip = false
	    }
	}
EOF

mkdir --parents "${HOME}/.config/onboard/"
tee "${HOME}/.config/onboard/onboard-defaults.conf" <<-EOF
	[main]
	layout=Flat
	theme=Flat
	show-status-icon=False
	show-tooltips=False
	start-minimized=True

	[window]
	force-to-top=True

	[window.landscape]
	height=380
	width=1200

	[icon-palette]
	in-use=True

	[icon-palette.landscape]
	height=100
	width=100
EOF

mkdir --parents "${HOME}/.local/share/onboard/layouts/"
wget --directory-prefix="${HOME}/.local/share/onboard/layouts/" "https://raw.githubusercontent.com/kontextwechsel/onboard-theme/master/layouts/Flat.onboard"

mkdir --parents "${HOME}/.local/share/onboard/themes/"
wget --directory-prefix="${HOME}/.local/share/onboard/themes/" "https://raw.githubusercontent.com/kontextwechsel/onboard-theme/master/themes/Flat.colors"
wget --directory-prefix="${HOME}/.local/share/onboard/themes/" "https://raw.githubusercontent.com/kontextwechsel/onboard-theme/master/themes/Flat.theme"

mkdir --parents "${HOME}/.local/share/icons/"
tee "${HOME}/.local/share/icons/terminal.xpm" <<-EOF
	/* XPM */
	static char *terminal[] = {
	/* columns rows colors chars-per-pixel */
	"32 32 62 1 ",
	"  c #000000",
	". c #0B0D0C",
	"X c #131616",
	"o c #151817",
	"O c #161919",
	"+ c #1A1C1B",
	"@ c #1C201F",
	"# c #1E2221",
	"$ c #232625",
	"% c #232826",
	"& c #262B2A",
	"* c #2A2D2C",
	"= c #2A312F",
	"- c #2E3532",
	"; c #323534",
	": c #313836",
	"> c #353D3A",
	", c #3C3E3C",
	"< c #37403D",
	"1 c #3B413F",
	"2 c #41433F",
	"3 c #3D4542",
	"4 c #3E4845",
	"5 c #434543",
	"6 c #434946",
	"7 c #484A46",
	"8 c #434D4A",
	"9 c #4B4D4A",
	"0 c #46524E",
	"q c #4B524E",
	"w c #51534E",
	"e c #4B5552",
	"r c #4E5A55",
	"t c #525553",
	"y c #535855",
	"u c #5A5C56",
	"i c #545C5A",
	"p c #5A5D5B",
	"a c #55625D",
	"s c #5C615D",
	"d c #61635D",
	"f c #566460",
	"g c #5B6461",
	"h c #636562",
	"j c #6D6E6D",
	"k c #707170",
	"l c #868686",
	"z c #898B89",
	"x c #9F9F9F",
	"c c #9DA09F",
	"v c #A0A0A0",
	"b c #B4B5B5",
	"n c #B9BABA",
	"m c #C6C6C6",
	"M c #CBCBCB",
	"N c #D3D3D3",
	"B c #DCDCDC",
	"V c #E3E3E3",
	"C c #EBEBEB",
	"Z c #F4F4F4",
	"A c #FBFBFB",
	"S c None",
	/* pixels */
	"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
	"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
	"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
	"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
	"SShdddddhdddddddhdddddddddddhSSS",
	"ShzxxxxxxxxxxxxxxxxxxxxxxxxxzhSS",
	"SdNNNBBVVCCCZZAAAAZZCCCVVBBNNdSS",
	"SdMXoXXXXXOXXO+O+oOOO+++++XXNdSS",
	"SsMX   . ....;pt9*..\$95,*\$OXNuSS",
	"SpMXXv+++++@@ehpt*##tpq5,;\$XMuSS",
	"SuMo.*nXXo+++tpy5++;pt7,;*@XNuSS",
	"SuMX+b1\$\$&&**hhp5**phte6,;*XMuSS",
	"SuMXXO+@#$%%-pit*&1pyq6<;&\$XMuSS",
	"SyMX$&*zcc:>6gge>1ggptq5,;\$XMtSS",
	"StMX@#%7ey--6iy4>4ite85>-%+OMwSS",
	"SwMX*=::,<33rsi88ggpy963:-*oMwSS",
	"SqmX#&=-><<3eee40it044<-=&%XM9SS",
	"SqMX::><444eiariaaite441<:-XM0SS",
	"Sqmo&=:><3440errre0444<>:=&XM9SS",
	"S7mX:<<3400raaffffiir444<<:XMqSS",
	"S9mX==:<344eeraffre444<<--*Xm9SS",
	"S7mX-<<444eriaffffaiee441>:Xm6SS",
	"S5mX&=-><44400ee04e444<:--&Xm6SS",
	"S5mX--<<344000eeeee4444<::-Om5SS",
	"S5mXX+OOoo+ooo+Ooo+oo+ooOOOOm2SS",
	"S2mmmmmmmmmmmmmmmmmmmmmmmmmmm3SS",
	"S2jlllllllllzlllllllllllllllk2SS",
	"S+,,,,,,,,,,,,,,,,,,,,,,,,,,,+SS",
	"SS                            SS",
	"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
	"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
	"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"
	};
EOF
tee "${HOME}/.Xresources" <<-EOF
	Xft.dpi: 96
	XTerm.termName: xterm
	XTerm.title: Terminal
	XTerm.iconHint: ${HOME}/.local/share/icons/terminal
	XTerm.VT100.faceName: Source Code Pro
	XTerm.VT100.faceSize: 18
	XTerm.VT100.allowBoldFonts: false
	XTerm.VT100.background: rgb:28/28/28
	XTerm.VT100.foreground: rgb:f7/f7/f7
	XTerm.VT100.color0: rgb:6f/6f/6f
	XTerm.VT100.color1: rgb:f9/24/72
	XTerm.VT100.color2: rgb:a6/e2/2c
	XTerm.VT100.color3: rgb:e7/db/74
	XTerm.VT100.color4: rgb:67/d8/ef
	XTerm.VT100.color5: rgb:ac/80/ff
	XTerm.VT100.color6: rgb:2a/a1/98
	XTerm.VT100.color7: rgb:f8/f8/f8
	XTerm.VT100.color8: rgb:28/28/28
	XTerm.VT100.color9: rgb:f9/24/72
	XTerm.VT100.color10: rgb:a6/e2/2c
	XTerm.VT100.color11: rgb:e7/db/74
	XTerm.VT100.color12: rgb:67/d8/ef
	XTerm.VT100.color13: rgb:ac/80/ff
	XTerm.VT100.color14: rgb:2a/a1/98
	XTerm.VT100.color15: rgb:f7/f7/f7
	XTerm.VT100.alternateScroll: true
	XTerm.VT100.fastScroll: true
	XTerm.VT100.jumpScroll: true
	XTerm.VT100.multiScroll: true
	XTerm.VT100.on2Clicks: regex (https?:)?[a-zA-Z0-9$%&/()?@~*+#,._-]+
	XTerm.VT100.on3Clicks: line
	XTerm.VT100.saveLines: 16384
	XTerm.VT100.translations: #override \\n\\
	    Shift Ctrl <Key> c: copy-selection(CLIPBOARD) \\n\\
	    Shift Ctrl <Key> v: insert-selection(CLIPBOARD)
EOF

tee "${HOME}/.xinitrc" <<-EOF
	xrdb -merge "\${HOME}/.Xresources"
	exec /usr/bin/openbox-session > /dev/null 2>&1
EOF

tee "${HOME}/.bash_profile" <<- EOF
	if [[ -n "\${BASH_VERSION}" && -f "\${HOME}/.bashrc" ]]; then
	    source "\${HOME}/.bashrc"
	fi
	if [[ -z "\${DISPLAY}" && "\${XDG_VTNR}" -eq 1 ]]; then
	    exec startx
	fi
EOF

tee "${HOME}/.bashrc" <<- EOF
	if [[ "\$-" = *i* ]]; then
	  if [[ -z "\${SSH_CLIENT:+substitution}" ]]; then
	    PS1="\[\e[32m\]\u@\h\[\e[m\]:\[\e[34m\]\w\[\e[m\]\\\$ "
	  else
	    PS1="\[\e[31m\]\u@\h\[\e[m\]:\[\e[34m\]\w\[\e[m\]\\\$ "
	  fi

	  export EDITOR="vim"
	  export PAGER="less"
	  export SYSTEMD_PAGER="cat"

	  alias sudo="sudo --preserve-env=EDITOR,PAGER,SYSTEMD_PAGER"

	  HISTCONTROL="ignoreboth"
	  HISTFILE="\${HOME}/.bash_history"
	  HISTFILESIZE="-1"
	  HISTSIZE="-1"
	  HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S "

	  shopt -s autocd
	  shopt -s checkwinsize
	  shopt -s globstar
	  shopt -s histappend
	  tabs 4

	  eval "\$(dircolors -b)"

	  alias bc="/usr/bin/bc --mathlib"
	  alias diff="/usr/bin/diff --color=auto"
	  alias grep="/usr/bin/grep --color=auto"
	  alias ip="/usr/bin/ip -color=auto"
	  alias less="/usr/bin/less --ignore-case"
	  alias ls="/usr/bin/ls --color=auto --group-directories-first"

	  for command in poweroff reboot suspend hibernate; do
	    alias "\${command}"="/usr/bin/systemctl \${command}"
	  done

	  function toogle_history() {
	    if [[ -z "\${HISTFILE:+substitution}" ]]; then
	      HISTFILE="\${HOME}/.bash_history"
	      printf "\e[30mHistory enabled\e[0m\n"
	    else
	      unset HISTFILE
	      printf "\e[30mHistory disabled\e[0m\n"
	    fi
	  }
	  bind -x '"\eh": toogle_history'

	  if [[ -r /usr/share/bash-completion/bash_completion ]]; then
	    . /usr/share/bash-completion/bash_completion
	  fi
	fi
EOF

tee "${HOME}/.bash_logout" <<- EOF
EOF

tee "${HOME}/.hushlogin" <<- EOF
EOF
